spring.application.name=ingestion-service

server.port=${SERVER_PORT:8082}

#Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
spring.kafka.template.default-topic=energy-usage
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer




# Continuous simulation configuration
simulation.endpoint=${SIMULATION_ENDPOINT:http://localhost:8082/api/v1/ingestion}
simulation.requests-per-interval=${SIMULATION_REQUESTS_PER_INTERVAL:10000}
simulation.interval-ms=${SIMULATION_INTERVAL_MS:60000}
simulation.parallel-threads=${SIMULATION_PARALLEL_THREADS:10}

# Device service API endpoint for parallel simulation
device.service.url=${DEVICE_SERVICE_URL:http://localhost:8081/api/v1/device}